ASP_2184587/Models/proveedor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_2184587.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proveedor()
        {
            this.producto = new HashSet<producto>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string nombre_contacto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto { get; set; }
    }
}

ASP_2184587/Controllers/ProveedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASP_2184587.Models;
using System.IO;


namespace ASP_2184587.Controllers
{
    [Authorize]
    public class ProveedorController : Controller
    {
        // GET: Proveedor
        [Authorize]
        public ActionResult Index()
        {
            using (var db = new inventarioEntities())
            {
                return View(db.proveedor.ToList());
            }
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(proveedor proveedor)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            try
            {
                using (var db = new inventarioEntities())
                {
                    db.proveedor.Add(proveedor);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Error - Datos ingresados de manera erronea");
                return View();
            }
        }
        public ActionResult Details(int id)
        {
            using (var db = new inventarioEntities())
            {
                var findProv = db.proveedor.Find(id);
                return View(findProv);
            }
        }
        public ActionResult Edit(int id)
        {
            try
            {
                using (var db = new inventarioEntities())
                {
                    proveedor findProv = db.proveedor.Where(a => a.id == id).FirstOrDefault();
                    return View(findProv);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error" + ex);
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(proveedor editProv)
        {
            try
            {
                using (var db = new inventarioEntities())
                {
                    proveedor prov = db.proveedor.Find(editProv.id);

                    prov.nombre = editProv.nombre;
                    prov.direccion = editProv.direccion;
                    prov.telefono = editProv.telefono;
                    prov.nombre_contacto = editProv.nombre_contacto;

                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Error - Datos ingresados de manera erronea");
                return View();
            }
        }
        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = new inventarioEntities())
                {
                    var findProv = db.proveedor.Find(id);
                    db.proveedor.Remove(findProv);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error" + ex);
                return View();
            }
        }

        public ActionResult UploadCSV()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadCSV(HttpPostedFileBase ArchivoFormulario)
        {
            //Guardar la ruta
            string FilePath = string.Empty;

            //Saber si llego el archivo
            if (ArchivoFormulario != null)
            {
                //Ruta de la carpeta que carga el archivo
                string path = Server.MapPath("~/Uploads/");

                //Verificar si la ruta de la carpeta existe
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                //Obtener el nombre del archivo
                FilePath = path + Path.GetFileName(ArchivoFormulario.FileName);
                //Obtener la extension
                string extension = Path.GetExtension(ArchivoFormulario.FileName);
                //Guardar el archivo
                ArchivoFormulario.SaveAs(FilePath);

                string CSVData = System.IO.File.ReadAllText(FilePath);
                foreach (string row in CSVData.Split('\n'))
                {
                    if (!string.IsNullOrEmpty(row))
                    {
                        var NuevoProveedor = new proveedor
                        {
                            nombre = row.Split(';')[0],
                            nombre_contacto = row.Split(';')[1],
                            direccion = row.Split(';')[2],
                            telefono = row.Split(';')[3]
                        };
                        using (var db = new inventarioEntities())
                        {
                            db.proveedor.Add(NuevoProveedor);
                            db.SaveChanges();
                        }
                    }
                }

            }
            return RedirectToAction("Index");
        }
    }
}

ASP_2184587/Views/Proveedor/Create.cshtml
@model ASP_2184587.Models.proveedor

@{
    ViewBag.Title = "Crear Proveedor";
}

<h2>Crear Proveedor</h2>
<p>En este formulario se puede registrar datos del Proveedor.</p>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2" for="nombre">Nombre</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="direccion">Direccion</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="telefono">Telefono</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="nombre_contacto">Nombre de Contacto</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre_contacto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre_contacto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Regresar a la Lista", "Index", "", new { @class = "btn btn-default", @role = "button" })
    @Html.ActionLink("Archivo .CSV", "UploadCSV", "", new { @class = "btn btn-default", @role = "button" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ASP_2184587/Views/Proveedor/Details.cshtml
@model ASP_2184587.Models.proveedor

@{
    ViewBag.Title = "Detalles de Proveedor";
}

<h2>Detalles de Proveedor</h2>
<p>En este formulario se pueden visualizar los datos especificos del proveedor seleccionado.</p>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nombre
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            Direccion
        </dt>

        <dd>
            @Html.DisplayFor(model => model.direccion)
        </dd>

        <dt>
            Telefono
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            Nombre de Contacto
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre_contacto)
        </dd>

    </dl>
</div>
<p>
    <div>
        @Html.ActionLink("Editar", "Edit", new { id = Model.id }, new { @class = "btn btn-default", @role = "button" })
        @Html.ActionLink("Regresar a la Lista", "Index", "", new { @class = "btn btn-default", @role = "button" })
    </div>
</p>

ASP_2184587/Views/Proveedor/Edit.cshtml
@model ASP_2184587.Models.proveedor

@{
    ViewBag.Title = "Editar Proveedor";
}

<h2>Editar Proveedor</h2>
<p>En este formulario se puede editar los datos del proveedor seleccionado.</p>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            <label class="control-label col-md-2" for="nombre">Nombre</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="direccion">Direccion</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="telefono">Telefono</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="nombre_contacto">Nombre de Contacto</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre_contacto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre_contacto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la Lista", "Index", "", new { @class = "btn btn-default", @role = "button" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ASP_2184587/Views/Proveedor/Index.cshtml
@model IEnumerable<ASP_2184587.Models.proveedor>

@{
    ViewBag.Title = "Lista de Proveedores";
}

<h2>Lista de Proveedores</h2>
<p>Listado de Proveedores registrado en el Sistema de Informacion.</p>

<p>
    @Html.ActionLink("Crear Proveedor", "Create", "", new { @class = "btn btn-default", @role = "button" })
</p>
<table class="table table-bordered table-hover table-responsive">
    <tr>
        <th>
            Nombre
        </th>
        <th>
            Telefono
        </th>
        <th>Gestión</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.telefono)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.id }) |
                @Html.ActionLink("Detalles", "Details", new { id = item.id }) |
                @Html.ActionLink("Borrar", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>

ASP_2184587/Views/Proveedor/UploadCSV.cshtml
@{
    ViewBag.Title = "UploadCSV - Proveedor";
}

<h2>Cargar archivo CSV</h2>

@using (Html.BeginForm("UploadCSV","Proveedor",FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    <input type="file" name="ArchivoFormulario"/>
    <input type="submit" value="Enviar"/>
}