ASP_2184587/Controllers/CompraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASP_2184587.Models;

namespace ASP_2184587.Controllers
{
    [Authorize]
    public class CompraController : Controller
    {
        // GET: Compra        
        public ActionResult Index()
        {
            using (var db = new inventarioEntities())
            {
                return View(db.compra.ToList());
            }
        }
        public static string NombreUsuario(int? idUsuario)
        {
            using (var db = new inventarioEntities())
            {
                return db.usuario.Find(idUsuario).nombre;
            }
        }
        public static string NombreCliente(int? idCliente)
        {
            using (var db = new inventarioEntities())
            {
                return db.cliente.Find(idCliente).nombre;
            }
        }
        public ActionResult ListarUsuarios()
        {
            using (var db = new inventarioEntities())
            {
                return PartialView(db.usuario.ToList());
            }
        }
        public ActionResult ListarClientes()
        {
            using (var db = new inventarioEntities())
            {
                return PartialView(db.cliente.ToList());
            }
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(compra compra)
        {
            if (!ModelState.IsValid)
                return View();
            try
            {
                using (var db = new inventarioEntities())
                {
                    db.compra.Add(compra);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error" + ex);
                return View();
            }
        }
        public ActionResult Edit(int id)
        {
            using (var db = new inventarioEntities())
            {
                compra compraEdit = db.compra.Where(a => a.id == id).FirstOrDefault();
                return View(compraEdit);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(compra compraEdit)
        {
            try
            {
                using (var db = new inventarioEntities())
                {
                    compra anteriorCompra = db.compra.Find(compraEdit.id);
                    anteriorCompra.fecha = compraEdit.fecha;
                    anteriorCompra.total = compraEdit.total;
                    anteriorCompra.id_usuario = compraEdit.id_usuario;
                    anteriorCompra.id_cliente = compraEdit.id_cliente;

                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error" + ex);
                return View();
            }
        }
        public ActionResult Details(int id)
        {
            using (var db = new inventarioEntities())
            {
                var findUser = db.compra.Find(id);
                return View(findUser);
            }
        }
        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = new inventarioEntities())
                {
                    var findUser = db.compra.Find(id);
                    db.compra.Remove(findUser);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", "Error" + ex);
                return View();
            }
        }
    }
}

ASP_2184587/Controllers/ProductoCompraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASP_2184587.Models;

namespace ASP_2184587.Controllers
{
    [Authorize]
    public class ProductoCompraController : Controller
    {
        // GET: ProductoCompra
        [Authorize]
        public ActionResult Index()
        {
            using (var db = new inventarioEntities())
            {
                return View(db.producto_compra.ToList());
            }
        }
         public static string NombreProducto(int? idProducto)
        {
            using (var db = new inventarioEntities())
            {
                return db.producto.Find(idProducto).nombre;
            }
        }

        public ActionResult ListarCompra()
        {
            using (var db = new inventarioEntities())
            {
                return PartialView(db.compra.ToList());
            }
        }
        public ActionResult ListarProducto()
        {
            using (var db = new inventarioEntities())
            {
                return PartialView(db.producto.ToList());
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(producto_compra ProductoCompra)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            try
            {
                using (var db = new inventarioEntities())
                {
                    db.producto_compra.Add(ProductoCompra);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Error - Datos ingresados de manera erronea");
                return View();
            }
        }

        public ActionResult Details(int id)
        {
            using (var db = new inventarioEntities())
            {
                var finProCom = db.producto_compra.Find(id);
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            try
            {
                using (var db = new inventarioEntities())
                {
                    producto_compra findProCom = db.producto_compra.Where(a => a.id == id).FirstOrDefault();
                    return View(findProCom);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error" + ex);
                return View();
            }
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Edit (producto_compra editProCom)
        {
            try
            {
                using (var db = new inventarioEntities())
                {
                    producto_compra ProCom = db.producto_compra.Find(editProCom.id);

                    ProCom.id_compra = editProCom.id_compra;
                    ProCom.id_producto = editProCom.id_producto;
                    ProCom.cantidad = editProCom.cantidad;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", "Error" + ex);
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = new inventarioEntities())
                {
                    var findProCom = db.producto_compra.Find(id);
                    db.producto_compra.Remove(findProCom);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error" + ex);
                return View();
            }
        }
    }
}

ASP_2184587/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DOCX</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/css.css"/>
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DOCX", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav nav-pills">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Usuario", "Index", "Usuario")</li>
                        <li>@Html.ActionLink("Cliente", "Index", "Cliente")</li>
                        <li>@Html.ActionLink("Proveedor", "Index", "Proveedor")</li>
                        <li>@Html.ActionLink("Producto", "Index", "Producto")</li>
                        <li>@Html.ActionLink("Compras", "Index", "Compra")</li>
                        <li>@Html.ActionLink("Reporte", "Reporte", "Producto")</li>
                        <li>@Html.ActionLink("Producto Compra", "Index", "ProductoCompra")</li>
                        <li>@Html.ActionLink("Cerrar Sesion", "Logout", "Usuario", new { area = "" }, new { @class = "" })</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                        <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                        <li>@Html.ActionLink("Iniciar Sesion", "Login", "Usuario")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="footer">
            @RenderSection("infoFooter",required:false)
            <p class="P_Footer">&copy; @DateTime.Now.Year - DOCX |
            <a href="https://github.com/Francisco-Cifuentes/ASP_218458" target="_blank">Repositorio GitHub </a>|
            <a href="mailto:facifuentes04@misena.edu.co" target="_blank">Gmail SENA</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>